# To add fields, make a new schema file in this directory
# and change the schema setting in _config.yml to its name
dataset_fields:
  - field_name: title
    label: Title
    datajson: title
  - field_name: update_freq
    label: Uuendussagedus
    datajson: frequency
  - field_name: date_issued
    label: Lisatud Portaali (YYYY/MM/DD)
    datajson: issued
  - field_name: date_modified
    label: Viimati muudetud (YYYY/MM/DD)
    datajson: modified
  - field_name: organization
    label: Teabevaldaja
    datajson: publisher
  - field_name: notes
    label: Kirjeldus
    form_template: form/textarea.html
    datajson: description
  - field_name: license
    label: Kasutuslitsents
    form_template: form/license.html
    datajson: license
  - field_name: category
    label: Peamine teema
    form_template: form/category.html
    display_template: display/category.html
    datajson: category
  - field_name: maintainer_name
    label: Kontakt nimi
    datajson: contactPoint.fn
  - field_name: maintainer_email
    label: Kontakt Email
    datajson: contactPoint.hasEmail
  - field_name: maintainer_phone
    label: Kontakt telefon

dataset_fields_english:
  - field_name: title
    label: Title
    datajson: title_en
  - field_name: update_freq
    label: Update Frequency
    datajson: frequency
  - field_name: date_issued
    label: Added to Portal (YYYY/MM/DD)
    datajson: issued
  - field_name: date_modified
    label: Last Modified (YYYY/MM/DD)
    datajson: modified
  - field_name: organization
    label: Organization
    datajson: publisher
  - field_name: notes_en
    label: Notes
    form_template: form/textarea.html
    datajson: description
  - field_name: license
    label: Usage License
    form_template: form/license.html
    datajson: license
  - field_name: category_en
    label: Category
    form_template: form/category.html
    display_template: display/category_en.html
    datajson: category_en
  - field_name: maintainer_name
    label: Contact Name
    datajson: contactPoint.fn
  - field_name: maintainer_email
    label: Contact Email
    datajson: contactPoint.hasEmail
  - field_name: maintainer_phone
    label: Contact Phone

resource_fields:
  - field_name: name
    label: Resource Name
    datajson: distribution.title
  - field_name: url
    label: URL
    datajson: distribution.downloadURL
  - field_name: format
    label: Format
    datajson: distribution.format
    form_template: form/dropdown.html
    values:
      - api
      - csv
      - json
      - geojson
      - html
      - kml
      - kmz
      - shp
      - xml
      - xlsx
      - xsd
      - txt
      - zip
      - pdf
      - rdf

organization_fields:
  - field_name: title
    label: Title
  - field_name: maintainer_name
    label: Kontakt nimi
  - field_name: maintainer_email
    label: Kontakt Email
  - field_name: description
    label: Description
  - field_name: logo
    label: Logo

category_fields:
  - field_name: name
    label: Name
  - field_name: logo
    label: Logo
  - field_name: logo_credit
    label: Logo Credit
  - field_name: featured
    label: Featured on Homepage
    form_template: form/checkbox.html

application_fields:
  - field_name: app_name
    label: Application
  - field_name: developed_by
    label: Developer
  - field_name: app_description
    label: Description
  - field_name: submitted
    label: Submitted Date
  - field_name: app_url
    label: App URL
  - field_name: app_preview
    label: Preview Image

news_fields:
  - field_name: news_title
    label: Title
  - field_name: author
    label: Author
  - field_name: text
    label: Text
  - field_name: preview
    label: Preview
  - field_name: preview_image
    label: Image URL
  - field_name: submitted
    label: Kuupäev
